name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  update-submodules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Update submodules to latest commit
        run: |
          git submodule update --remote --merge
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if git status --porcelain | grep .; then
            git add .
            git commit -m "Update submodules to latest commits"
            git push
          else
            echo "No submodule updates needed"
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: update-submodules
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
